### ISSUE TITLE
When multiple clients are used in parallel, EmbedIO has lots of read timeouts 

### ISSUE THREAD

**Issue by nddipiazza** [unosquare/embedio#224]
**Describe the bug**
When using EmbedIO with an http client with multiple parallel threads (5 threads in my case), you start getting read timeouts.

**To Reproduce**
1. launch this project https://github.com/nddipiazza/SambaFetcher
2. with multiple threads, access this service. 
3. you will see many of the requests will work but many will return read timeouts. 

**Expected behavior**
expected no read timeouts. 

is there some configuration parameter i need to set so that the embed IO will not timeout in the face of multiple threads? 

this is something that could use some documentation for how to tune.

**Comment by k3z0** [comment]
Hi @nddipiazza:

I just test you project running 500 simultaneous threads. Each one makes 10 call to the server and it seems to work properly. I even use the SmbServerModule with **info** action and a local path and I get the expected answer.

Could you please send us the test code you are running in order to get the error?

**Comment by geoperez** [comment]
Status?

**Comment by nddipiazza** [comment]
Just did a big test on this. And I conclude that it was actually my http client that was the problem. Invalid issue, please close. thank you! 
your embedded web server kicks ass. i hope my example proves useful for documentation
