### ISSUE TITLE
Migration issues

### ISSUE THREAD

**Issue by pablonardone** [unosquare/embedio#231]
I have some problems migrating embedio library from version 1.16.1 to version 2.2.0.

I'm working in NET Framework 4.7.2 and before (with the version 1.16.1) in the "WebSocketsServer.OnClientConnected" event the "context" parameter was of type "System.Net.WebSockets.WebSocketContext" but now is of type "Unosquare.Labs.EmbedIO.IWebSocketContext". 

Before with "context.WebSocket" it was posible accesing the native websocket, but now it can not be done any more because "context.WebSocket" is of type "Unosquare.Net.WebSocket" that has no native websocket inside.

So, Is ther any way to access the native websocket from the new library? Also what is the diference between the types "Unosquare.Labs.EmbedIO.WebSocket" and "Unosquare.Net.WebSocket"?, because the first one does have a native websocket, but the second one (which is what I receive in the connection event) does not have it.

Thanks.

**Comment by geoperez** [comment]
Hello,

EmbedIO 2.0 introduced a new abstraction level between the HttpListener and the WebServer. New interfaces were created in order to access common functionality in EmbedIO own classes and System.Net. Previous to this change, the only way to choose Microsoft HttpListener and Unosquare HttpListener were via the target framework. Now it's possible to switch between them (as long the target framework has support for Microsoft implementation).

We introduce wrapper classes around the Microsoft implementation to match the interfaces, so that's why you got "Unosquare.Labs.EmbedIO.WebSocket" and "Unosquare.Net.WebSocket". The first one is a plain wrapper that you can cast from the interface and then use the [SystemWebSocket property](https://github.com/unosquare/embedio/blob/master/src/Unosquare.Labs.EmbedIO/WebSocket.cs#L30).

Let me know if you need additional information. Thanks for using EmbedIO and please star this project if you find it useful!

**Comment by pablonardone** [comment]
I needed to initialize the web server with the mode "HttpListenerMode.Microsoft".
Thank you very much.

**Comment by geoperez** [comment]
Can I close this issue now?

**Comment by pablonardone** [comment]
Yes, thanks.
