### ISSUE TITLE
No CancellationToken for WebApiController handlers

### ISSUE THREAD

**Issue by blipk** [unosquare/embedio#271]
If I use a custom module extended from WebModuleBase and use AddHandler to create the handlers, I have access to the cancellation token via the WebHandler delegate when requests are made.

Is there anyway to access the cancellation tokens for the requests when using a WebApiController with WebApiHandler attribute to create the handlers?

Sorry if I've missed something but this seems like it would be very useful, at least for my use case.

Thanks.

**Comment by geoperez** [comment]
It's a good idea to pass the Cancellation Token to the WebAPI. I will check how to add it.

**Comment by blipk** [comment]
Thanks it would be super useful, or perhaps even if there is an indirect way to access it in the mean time.

I made some revisions to my code to use a WebModuleBase extension and passed the ct from AddModule to a Task.Run() thread and it doesn't seem to cancel when the page load is stopped or closed.

Is the ct supposed to be cancelled when that happens? is there something I'm missing.

Thanks.

**Comment by geoperez** [comment]
Nop, the cancellation token that we have in the IWebModule comes from the RunAsync method of IWebServer. In other words:

1 - Your application has a CancellationTokenSource or a CancellationToken
2 - You Start the WebServer with RunAsync method passing the CancellationToken
3 - The CancellationToken is provided to the WebHandlers.

Then you can use the CancellationToken to know for example if the application request stops all the processing.

There is not a CancellationToken connected to interrupted connection. This is because usually, the TCP connection will just fail when the client disconnect.

**Comment by geoperez** [comment]
Can I close this issue?

**Comment by blipk** [comment]
Yes, thank you for the response.
