### ISSUE TITLE
Custom MimeType

### ISSUE THREAD

**Issue by bufferUnderrun** [unosquare/embedio#302]
Since few version of EmbedIO, Constants.MimeTypes is IReadOnlyDictionary and i can't be modified. 

I used to add a custom extension ".tag" "text/html", which is not part of any RFC but used by the https://riot.js.org/. I had to do it for browsere correcttly handle this content type.

Can this extension be added to Constant ?

**Comment by rdeago** [comment]
Hello @bufferUnderrun, thanks for finding a use case for custom MIME types in EmbedIO.

I'm not exactly comfortable with the idea of adding an application-specific type to the standard MIME type dictionary. There is a way to support custom  types, though. What if there were a custom type dictionary and some utility functions that can find a MIME type by searching in both the standard and custom types?

If you think this fits your needs, it can be implemented in version 3.0 (whose release is not so far in the future as might have seemed a few days ago).

---

You're also invited to [join us on EmbedIO's Slack workspace](https://join.slack.com/t/embedio/shared_invite/enQtNjI5NDQwMjI2ODA0LTk5YzMwZjMwNjIzY2ZlYTZkYmI2MzUxNzIwYjAyMWZjZGI3ZTMxZDcxYWMyNzVjZDQ0ZTBiZGFmYWVlZjZiMmU), where implementation details may be discussed in a more interactive fashion.

**Comment by bufferUnderrun** [comment]
I agree that adding specific extension to Constant is not a good thing but it would have a way to add custom one.

In previous version of EmbedIO, i had this simple code to do the job before server starts : 
```C#
Unosquare.Labs.EmbedIO.Constants.MimeTypes.DefaultMimeTypes.Value.Add(".tag", "text/html")
```

**Comment by bufferUnderrun** [comment]
@rdeago i'm joining you on slack, i've never used before. So let's go.

**Comment by rdeago** [comment]
> @rdeago i'm joining you on slack, i've never used before. So let's go.

Great! As soon as some details have been discussed, I'll post a summary here.

**Comment by geoperez** [comment]
The new nuget version 2.8.0 is out!

**Comment by rdeago** [comment]
I promised a summary of our discussion on Slack, so here it is. You never know if / when someone needs to look at a past issue!

---

As it turned out, `DefaultMimeTypes` being read-only was a bug I introduced in a7f0adaca474b6235137f82e4155011b4108ee53. Due to the sheer size of the commit, and some undeserved trust in yours truly, @geoperez approved it without noticing the breaking change.

Commit 8173904c5e331c65d3eccd519e9cbbe0f555ede5 somehow reverses that change: `DefaultMimeTypes` is now a `ConcurrentDictionary` whose `IDictionary` interface is public.

Two more potentially breaking change remain, both related to the `FilesModuleBase.MimeTypes` property being but an alias of `DefaultMimeTypes`:
* since a7f0adaca474b6235137f82e4155011b4108ee53 it is no longer a static copy of `DefaultMimeTypes`, instead reflecting changes made to it over time (I chose not to revert _too much_, in case someone using latest versions relies on this feature);
* since 8173904c5e331c65d3eccd519e9cbbe0f555ede5, it is read-write too.
