### ISSUE TITLE
Error when requesting a wav file using chrome 🔉🚫

### ISSUE THREAD

**Issue by k3z0** [unosquare/embedio#310]
**Describe the bug**
Getting ERR_CONTENT_DECODING_FAILED when requesting for a wav file using chrome.

![imagen](https://user-images.githubusercontent.com/5455304/60134259-b9b9dc00-9764-11e9-9f80-9269046c30e1.png)

![imagen](https://user-images.githubusercontent.com/5455304/60134115-6b0c4200-9764-11e9-9b2e-ddbc10a23bd0.png)

**Comment by rdeago** [comment]
Thanks a lot @k3z0 for your input!

The problem here seems to originate in content encoding negotiation: Chrome is clearly stating, via the `Accept-Encoding` header, that it will not accept anything but uncompressed data, but it is _probably_ responded to with gzipped data.

Any chance you can post the response headers too?

Meanwhile, I'm writing some sorely needed unit tests for content encoding negotiation. Maybe they can put us on the right track to solve this issue.

**Comment by rdeago** [comment]
Unit testing _did_ help. 😁 

A bug in how `Accept-Encoding` request headers are parsed was found and fixed in f8b4e0d9fd7c28344f102e1e56426f3119692fbc.

@k3z0 you may either check out the v3.0 branch and build a "fresh" `EmbedIO.dll` yourself, or wait for @geoperez to push next preview to NuGet. Either way, please let us know whether the problem is solved.

**Comment by geoperez** [comment]
I updated the Nuget, let me know if it is resolved.

**Comment by k3z0** [comment]
Hi, 

I just test the preview4 and the problem seems to be solved.
