### ISSUE TITLE
Startup deadlock

### ISSUE THREAD

**Issue by AbeniMatteo** [unosquare/embedio#318]
**Describe the bug**
Deadlock if there is an error during server startup (in this case trying to bind multiple instances to the same port)

**Cause**
`server2.Start` waits [here](https://github.com/unosquare/embedio/blob/4f21893dac043c2875fed1c00b76830649071da3/src/EmbedIO/WebServerExtensions.cs#L26) for `Listening` state but state remains `Loading`.

**To Reproduce**
Run the following snippet:
```cs
var server1 = new WebServer(12345);
server1.Start();

var server2 = new WebServer(12345);
server2.Start();
```

**Version**
3.0.0-preview7

**Comment by rdeago** [comment]
Hello @AbeniMatteo, thanks a lot for your input.

Good catch, by the way!

The issue has been fixed in https://github.com/unosquare/embedio/commit/1bde6311263b8534425ca84721439c6f93e79257. Referring to your example code, now the call to `server2.Start` returns and `server2.State` equals `WebServerState.Stopped`.

**Comment by geoperez** [comment]
Also, you can check the nuget preview 8.
