### ISSUE TITLE
Request: Improve WebModuleBase.IsFinalHandler 

### ISSUE THREAD

**Issue by AbeniMatteo** [unosquare/embedio#321]
I understand why the default is true but i think it should be abstract or well document or at least logged.
The majority of the cases that require a custom implementation of WebModuleBase will need to set the value to false.

**Comment by rdeago** [comment]
I think making it abstract could be a good idea, but I frankly don't see why the majority of custom Web modules would need to set `IsFinalHandler` to false.

Just to clarify: `IsFinalHandler` does not mean that subsequent modules will not be invoked _at all_. It just means that a module "owns" its `BaseUrlPath`, so it will _normally_ handle requests whose URL path starts with the module's `BaseUrlPath`.

EmbedIO v3.0 (from preview 8 onwards, at least) stops passing a HTTP context to modules as soon as, when a module's `HandleRequestAsync` returns<sup>**1**</sup>, the context's `Handled` property is true. All the `IsFinalHandler` property does is tell EmbedIO to automatically set `context.Handled` to true, relieving the module's author from the burden of remembering to set it before returning from `HandleRequestAsync`.

This mechanism works well for a module that "owns" its part of the URL "tree", that is, either it can serve a URL that starts with `BaseUrlPath`, or no other module can.

Let's take `FileModule` as an example. Given a `FileModule` whose  `BaseUrlPath` is `/assets`, what happens when a client makes a request for `/assets/some/file/that/does_not.exist`?

* In EmbedIO v2, the `HandleRequestAsync` method of `StaticFileModule` (file-serving modules had not been unified yet) would return `false` and the request would be passed along to subsequent modules, none of which (in 99.99% of cases) would even match the requested URL path, leading to a `404 Not Found` response.

* In EmbedIO v3, the `HandleRequestAsync` method of `StaticFileModule` will (by default<sup>**2**</sup>) throw a `HttpException` in order to skip all subsequent processing and generate a `404 Not Found` response at once. In other words, the module is saying "I own URL paths that start with `/assets` and it's up to me to decide whether something is there or not."

Usually, a module that does not own its `BaseUrlPath` is a "filter" module, whose purpose is to check for some condition and, unless it detectes an anomaly, pass the request on to other modules. Examples of this are `CorsModule` and `BasicAuthenticationModule`. For most requests, such a module has no need to have `context.Handled` set to true on its behalf; on the contrary, this would defy the module's very purpose. Therefore, such modules have their `IsFinalHandler` getter return false.

Regardless of the value of `IsFinalHandler`, there is always a way for a module to pass a request through to other modules, and there is always a way to not do so. The following table summarizes how a module can trigger each behavior (pass-through or stop) in its `HandleRequestAsync` method:

| Value of `IsFinalHeader` | Pass-through                          | Stop            |
| :----------------------: | :------------------------------------ | :-------------- |
| `true`                   | `throw RequestHandler.PassThrough();` | Just return     |
| `false`                  | Just return                           | `context.Handled = true;` before returning |

As you can see, the difference is in what happens _by default_, as well as in the performance cost of deviating from such default. I foresaw the need to pass-through to be an exceptional occurrence for modules that own their "share" of URL paths, so it may be done by throwing a "special" kind of exception, that is created by the static `RequestHandler.PassThrough` method.

So, @AbeniMatteo, are most custom modules "filter" modules? Do they fit in another category of modules I didn't even think of? Or did I underestimate the need to pass a request through? Please help me understand, so that we may improve EmbedIO together, for the benefit of everyone using it.

Possible changes, in order to better address the needs of most users, may be:

* changing the default value of `IsFinalHandler`;

* making `IsFinalHandler` abstract;

* renaming `IsFinalHandler` to something more meaningful from the point of view of a module developer (`AutoHandle`, `OwnsUrlPaths`... suggestions are welcome;)

* ... (again, suggestions are welcome.)

---
<sup>**1**</sup>) I use the verb "to return" in a broad sense, meaning "to bring the returned `Task` to completion".

<sup>**2**</sup>) This behavior is customizable on a per-module basis, as are other reactions to specific events: see the `OnMappingFailed`, `OnDirectoryNotListable`, and `OnMethodNotAllowed` properties of `FileModule`.

**Comment by rdeago** [comment]
@geoperez @mariodivece @k3z0 
@bufferUnderrun @madnik7 @Genteure @jusovsky @mrsmidge
(sorry if I forgot someone)

Any thoughts?

**Comment by AbeniMatteo** [comment]
I wrote this request because i already have to deal with it, i'll describe what i've encoutered:

I have the following authentication module (filter):
```cs
if (authenticationValid)
{
    return false; // Not handled, let the WebApiModule respond
}
else
{
    StatusCode = 403;
    return true; // Request blocked, stop now
}
```

In this case i explicitly return false telling the WebServer that i don't have handled the request but `IsFinalHandler` by default will block all other modules setting `Handled = true`.
I think most new users (like me) will implement a filter like this one and will waste 30 mins trying to understand why, even explicitly saying "no i don't have handled this request", the execution stops.

Maybe the problem is that `IsFinalHandler` doesn't differentiate from Handled = false (the implementation hasn't set it) and Handled = false (the user have explicitly set it).
Or mayble i'm stuck with v2 logics of `Task<bool>` as result of the requests.

Those are the base modules implemented in this project and most of the are filters:

Module|IsFinalHandler
|-|-|
ActionModule|**false**
RedirectModule|**false**
BasicAuthenticationModule|**false**
CorsModule|**false**
FileModule|true
ModuleGroup|true
RoutingModuleBase|true
WebSocketModule|**false**

**Comment by rdeago** [comment]
Looking at the code you posted I'd say that yes, you are in fact a little stuck with v2 logic. That's not your fault: the new `RequestHandlerCallback` signature and the `IHttpContext.Handled` property, together with all related modifications, are still pretty new and sorely need documentation.

A version of your code in "v3-style" would be as follows:

```cs
protected override bool IsFinalHandler => false;

protected override async HandleRequestAsync(IHttpContext context, string path, CancellationToken cancellationToken)
{
    if (!IsAuthenticationValid(context))
        throw HttpException.Unauthorized("Authentication failed."); // The message is optional
}

private bool IsAuthenticationValid(IHttpContext context)
{
    // You know what to do here ;-)
}
```

This way, if the client provides a valid authentication, the module just returns and, since `IsFinalHandler` is false, the request gets passed along to other modules. Otherwise, instead of setting a status code and, potentially, sending an eror message, `HandleRequestAsync` throws an exception that tells the server to do the same things.

Why is `throw HttpException.Unauthorized()` preferrable over generating your own response (which is still supported - just remember `context.Handled = true;` before returning)? Because responses triggered by HTTP exceptions are customizable. You can decide whether you want the client to receive a simple `text/plain` message (or no message at all), or a nice HTML page, or even JSON data; this feature is orthogonal to the module's functionality. See the `IWebModule.OnHttpException` and `IWebServer.OnHttpException` properties, as well as the `HttpExceptionHandler` class, for more information.

Finally, why do most standard modules (besides the two that are obviously filters) set `IsFinalHandler` to `false`?

* `ActionModule` and `RedirectModule` are not filters, but they _contain_ filters, in that they can be set to only respond to specific HTTP methods. They have, potentially, quite a lot of requests to pass through, so I opted to save the cost of throwing an exception. They are standard library modules, after all, and as such they deserve some micro-optimization.

* `WebSocketModule` can (and should) set `IsFinalHandler` to `true`. I'm going to correct this in an incoming commit. Thanks for the heads-up!

* `ModuleGroup`, now that I think of it, is just plain wrong as it is: it should take the value of `IsFinalHandler` from a constructor parameter. Again, thank you for spotting the inconsistency.

**Comment by AbeniMatteo** [comment]
I'm sorry to be pedantic but i think the way to determine if the module has handled the request is very error prone.
I'll list few example:
- Setting `context.Handled` in a method of `WebApiController` doesn't do anything and in fact doesn't even make sense (we're inside a controller not a module).
- Setting `context.Handled = false` inside `WebModuleBase.OnRequestAsync` will be overriden by `WebModuleBase.IsFinalHandler` if true.
- Setting `context.Handled = false` inside `WebModuleBase.OnRequestAsync` will be overriden by [this line](https://github.com/unosquare/embedio/blob/f8c8a9727c928f581abc1f6565c7ac230f9ea75f/src/EmbedIO/Actions/ActionModule.cs#L52), the only way to set it to `false` is throwing an exception.

Suggesting few ideas and commenting on what @rdeago suggested [here](https://github.com/unosquare/embedio/issues/321#issuecomment-513140362):

- `IsFinalHandler` default value (false) is the safest but it will be better making it `abstract` to force the module implementation\implementer to be specific about the intentions (and think about it).
- I think the name `IsFinalHandler` is pretty clear.
- Throwing an exception if `HttpContext.Handled` is modified inside [this call](https://github.com/unosquare/embedio/blob/aed2530b42270febecc7e2a75da0aceb66d4ceff/src/EmbedIO/WebModuleBase.cs#L94) for modules having `IsFinalHandler = true` will remove the ability to set a value that will not be considered.

**Comment by geoperez** [comment]
Agree to make the `IsFinalHandler` property `abstract`.

**Comment by rdeago** [comment]
@AbeniMatteo we're talking about technical choices that will influence a number of projects for some time to come. Thus, I can assure you, I'm all for pedantry. Just ask @geoperez how pedantic I can be myself! 😁

So let me take my turn to be pedantic:

* Setting `context.Handled` in a web API controller method, as well as in the `OnRequestAsync` method of a module whose `IsFinalHandler` property is `true`, doesn't make sense. Of course. But why should anyone do that? What would they be trying to achieve? If there is something (in naming, semantics, even documentation or lack of it) that makes it appear as if setting `context.Handled` should actually do something meaningful, then _that_ must be corrected. Setting `context.Handled` _just because_, on the other hand, doesn't make sense, just as anything done _just because_.

* Setting `context.Handled` to `false` doesn't make sense _at all_, as it is already `false` _by definition_. If it were `true`, the `OnRequestAsync` or controller method that sets it to `false` would not have been called.

* Setting `context.Handled` to `false` when it is `true` _is_ a nonsense. As a matter of fact, it will result in an `InvalidOperationException` being thrown. Once a context is handled (hence a meaningful response generated) you cannot "unhandle" it.

* Last but not least, I fail to see how [an instruction in `ActionModule`](https://github.com/unosquare/embedio/blob/f8c8a9727c928f581abc1f6565c7ac230f9ea75f/src/EmbedIO/Actions/ActionModule.cs#L52) can override anything in other module types.

Notwithstanding the points above, I greatly appreciate how you're being constructive. Your suggestions make a lot of sense to me and are a precious help in this phase, that should be the final rush to EmbedIO v3.0. As a matter of fact, I have already made `IsFinalHandler` abstract in the commit linked just above your last comment - you probably posted a few seconds later.

Considering how a writable `IHttpContext.Handled` property is being more confusing than helpful, I propose the following:

* Make `IHttpContext.Handled` read-only.

* Add a `IHttpContext.MarkAsHandled` method (the name is maybe a bit too verbose, could a simple `Done` do?)

* All else will stay the same, as `Handled` (or `IsHandled`, which at this point seems a more appropriate name) would be handled (no pun intended) "behind the scenes" the same way as now.

* What I would avoid is throwing if `MarkAsHandled` is called someplace where it doesn't make sense. It could cause unexpected exceptions in classes that don't have a `sealed` override for `IsFinalHandler` if a subclass overrides it to `true`. I have at least one specific scenario in mind where this could happen: I'll ask you to trust me on this for now, because this comment has already become verbose enough. 😄 I won't trade the chance for a user to do something that doesn't make sense but is essentially a no-op, for the chance for otherwise legitimate code to cause an exception because of other otherwise legitimate code that is not under its control (think a base class in a DLL and a derived class in an application).

**Comment by AbeniMatteo** [comment]
My point of view is the point of view of a user that doesn't know all the internals and comes from v2.
After discovering `IsFinalHandler` i thought `IsHandled` was tri-state flag (`true` by user choice, `false` by user choice, default aka `IsFinalHandler`). And this is why i was talking about `ActionModule` behavior.

The changes you proposed looks fine to me and using a method instead of a property removes all the ambiguities and the potential benefit from throwing an exception.

Thanks for the discussion.

**Comment by rdeago** [comment]
Although I shamefully forgot to mention this issue in the commit message, here's what's in https://github.com/unosquare/embedio/commit/0c0bda7cc27e73ad405e7d9d5d36e965e057f2cf:

* `IHttpContext.Handled` is now called `IsHandled` and is read-only.

* The new `IHttpContext.SetHandled()` method can be used to mark a HTTP context as handled.

@AbeniMatteo do you think it can be improved further? I'm not entirely satisfied with the `SetHandled` name, for example, but `MarkAsHandled` looked too verbose and `Done` too generic and detached from its usage context.

Thank you for the discussion; you're also invited to [join EmbedIO's Slack workspace](https://join.slack.com/t/embedio/shared_invite/enQtNjcwMjgyNDk4NzUzLWQ4YTE2MDQ2MWRhZGIyMTRmNTU0YmY4MmE3MTJmNTY4MmZiZDAzM2M4MTljMmVmNjRiZDljM2VjYjI5MjdlM2U)!

**Comment by madnik7** [comment]
Sorry, I hadn't read all the discussion so properly, just what you are talking about look strange for me.

> Just to clarify: IsFinalHandler does not mean that subsequent modules will not be invoked at all. It just means that a module "owns" its BaseUrlPath, so it will normally handle requests whose URL path start with the module's BaseUrlPath.

If I understand properly, It looks you are going in design a method to decide continue calling next registered module or not. OK. It is a pipeline. Why don't use "next(parametes)" pattern. Usually the modules call next module itself, not by setting a flag. In this case the registered module has complete control how to pass the parameters to the next module, filter, change or just stop the pipeline by not calling the next module.

**Comment by rdeago** [comment]
Hello @madnik7, glad to read from you again!

A pipeline is a fitting abstraction in this case, and the [Chain-of-responsibility pattern](https://en.wikipedia.org/wiki/Chain-of-responsibility_pattern) you mention, or a slight variation of it, can of course work. Although I can't speak for @geoperez and @mariodivece, EmbedIO's authors, I think they traded some flexibility for simplicity and ease of use.

**Comment by geoperez** [comment]
Hi @AbeniMatteo, did you test this new approach with the RC002 nuget?

**Comment by AbeniMatteo** [comment]
I was testing preview 9 and i also just tested RC002. Looks good to me.

One detail, updating from v2, `Task.ResultFrom(bool)` as result for non async `WebModuleBase.OnRequestAsync` will still work. This might cause some problem if not considered.
If there are instructions about the upgrade from v2 to v3, i think it should be mentioned to pay attention to avoid this problem.

**Comment by geoperez** [comment]
We are starting the upgrade notes here: https://github.com/unosquare/embedio/wiki/Upgrade-from-v2

**Comment by rdeago** [comment]
Closing this issue, as the problem stated in the original post has been solved.
