### ISSUE TITLE
Reintroduce module-level routing in v3.0

### ISSUE THREAD

**Issue by rdeago** [unosquare/embedio#334]
RequestRegexUrlParams() doesn't exist in 3.0 - how do we route in a websocket now?

_Originally posted by @momo-the-monster in https://github.com/unosquare/embedio/issues/123#issuecomment-518388506_

**Comment by rdeago** [comment]
Hello @momo-the-monster, thanks for your input.

To make a long story short, module routing was scraped in favor of simple path prefixes. This was one of the first breaking changes introducerd in version 3, long before the first preview version came out. Since then, however, the route parser has been rewritten as a separate class, so now module routing could be reintroduced without much complication, with no source changes for applications already ported to v3.0, and negligible performance penalty for modules that do not have route parameters.

So, yes, routing is going to come back. I cannot work on it at the moment, but I'll dedicate some hours to it next week.

**Comment by rdeago** [comment]
This will be a breaking change at a binary level, due to changes in `IHttpContext`.

**Comment by rdeago** [comment]
Although I forgot to mention this issue in the commit message, 5433c67edcc49ef82e7f6da7a236f4be5162463b (re)introduces routing for modules.

Now you can use a route instead of a base URL path to initialize a module.

To get the route parameters from inside your handlers, use the new `IHttpContext.Route` property, whose type is [`EmbedIO.Routing.RouteMatch`](https://github.com/unosquare/embedio/blob/v3.0/src/EmbedIO/Routing/RouteMatch.cs).

**Comment by rdeago** [comment]
@momo-the-monster this should solve your problem about routing. Can you confirm?

**Comment by momo-the-monster** [comment]
Thanks @rdeago! I was indeed able to use this parameter within HTTP/Rest handlers.
I believe my original approach was based on a misunderstanding - I was thinking I wanted to handle different endpoints within a single Websocket in order to accept a variety of binary messages with different actions like "/submit", "/list", "/cancel", etc. However, a Websocket connection seems to want to be bound to a single endpoint, so it looks like I should instead just use a message format that specifies this action as part of the message instead of part of the route.

Thank you so much for the update and your response here!

**Comment by rdeago** [comment]
@momo-the-monster no problem. Module-level routing (or better, in v3.0 terms, module-container-level routing) is a feature that I had removed for performance reasons. Now I've added it back, but with some optimization for parameterless routes (i.e. simple prefixes). The performance impact should be little to negligible.
