### ISSUE TITLE
Wrong route handling

### ISSUE THREAD

**Issue by AbeniMatteo** [unosquare/embedio#347]
**To Reproduce**
Run the following snippet:
```cs
namespace Repro
{
    using EmbedIO;
    using EmbedIO.Routing;
    using EmbedIO.WebApi;
    using System.Text;

    class Program
    {
        static void Main()
        {
            var server = new WebServer(12345);
            server.WithModule(new WebApiModule("/").WithController<MyController>());
            server.RunAsync().Wait();
        }

        private class MyController : WebApiController
        {
            [Route(HttpVerbs.Get, "/")]
            public void GetIndex()
            {
                WriteText("index");
            }

            [Route(HttpVerbs.Get, "/page1.html")]
            public void GetPage1()
            {
                WriteText("page1");
            }

            private void WriteText(string content)
            {
                var data = Encoding.UTF8.GetBytes(content);
                using (var stream = HttpContext.OpenResponseStream())
                    stream.Write(data, 0, data.Length);
            }
        }
    }
}
```

**Expected behavior**
http://localhost:12345/page1.html handler should be `GetPage1` instead of `GetIndex`.
This happen only if there is a route registered for `/`. Works fine at least before `3.0.0-rc005` (the last version i tested before updating).

**Version**
3.0.1

**Comment by rdeago** [comment]
Hello @AbeniMatteo, glad to see you around again. :)

Another good catch! The problem lies in RouteMatcher's cache, that indexes matchers by route with no distinction between base (i.e. module's) and non-base (i.e. controller's) routes. Therefore, the "/" path is matched by the controller using the same Regex used by the WebApiModule, which does not require the path to be "/" but to _start_ with "/". That's why GetIndex gets called for "/page1.html".

A pull request is on its way.

**Comment by geoperez** [comment]
A new nuget was published.

**Comment by AbeniMatteo** [comment]
Works fine, thank you.
