### ISSUE TITLE
Sessions for each WebModule

### ISSUE THREAD

**Issue by Serk352** [unosquare/embedio#409]
EmbedIO is creating a session for each controller instead of one for all the WebModules.

**Comment by rdeago** [comment]
Hello @Serk352. This issue looks somewhat unlikely to me, because the session manager is defined at web server level, so it is the same for all modules, by definition.

Here are some tests you can do to verify that the problem is indeed the one you mention.

Given a `WebServer` with two modules and a `LocalSessionManager`:

* Does the client actually store cookies? This seems trivial, but `System.Net.Http.HttpClient` by default does not, as someone [on StackOverflow](https://stackoverflow.com/questions/17983992/httpclient-not-saving-cookies) discovered to their dismay.
* Is the session manager's `SessionDuration` property set to the default value (30 minutes) or is it set to some shorter value, maybe causing the session to be discarded between requests?
* Is the session manager's `CookieDuration` property set to the default value (zero, meaning "as long as the client retains the cookie") or is it set to some other value, maybe causing the cookie to be "forgotten" by the client between requests?
* Is session data retained between requests made to the same module?

I'm not entirely ruling out a bug in EmbedIO's session management; I'd just like to pinpoint it with sufficient precision, so we can eliminate it faster and add a meaningful regression test.

Of course, a (non-)working example would be mostly appreciated.

**Comment by rdeago** [comment]
@Serk352 any news? If this turns out to be an actual bug, the sooner it gets identified and fixed, the better.

**Comment by geoperez** [comment]
If you don't set the Path property of the Cookie in SessioMananger, each different path in WebAPI Controllers will create a new cookie.

**Comment by rdeago** [comment]
@geoperez so is there a bug in [`LocalSessionManager.BuildSessionCookie`](https://github.com/unosquare/embedio/blob/fc4eb943878963ec9c74ef8c2bd8b95809e29abc/src/EmbedIO/Sessions/LocalSessionManager.cs#L268-L281), that does not set the cookie's `Path`?

**Comment by geoperez** [comment]
Sorry, I miss this thread. Let me check the issue and document it.

**Comment by geoperez** [comment]
OK, the thing is that `LocalSessionManager` is always using string empty as Cookie Path by default. So you can't share a cookie between modules, because the string empty will change to the module base path.

You need to specify the Cookie Path to root, in order to share the cookie. Something like this:

```
WebServer.WithLocalSessionManager(m =>
                {
                    m.SessionDuration = TimeSpan.FromMinutes(10);
                    m.CookiePath = "/";
                })
```

Maybe this is your design, but it is just different from previous EmbedIO behavior.

**Comment by rdeago** [comment]
More than my design, this is most probably my fault.

So should I make `"/"` the default path for session cookies?

**Comment by geoperez** [comment]
I think we should. I'll add a PR with this patch later the week.
