### ISSUE TITLE
WebServer does not provide Content-Length when implementing FileModule 

### ISSUE THREAD

**Issue by madnik7** [unosquare/embedio#460]
**Describe the bug**
I implement IFileProvider and set the stream size by MappedResourceInfo.ForFile, but it looks the server does return Content-Length. Also downloaders report unknown file size

**To Reproduce**
It is tricky

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Latest Chrome

**Comment by rdeago** [comment]
Hello @madnik7, welcome back!

`FileModule` only sends a `Content-Length` header when the requested resource is cached, that is when both the following conditions are true:
* your module's `ContentCaching` property is `true`, and
* the requested file's size in KiBiBytes does not exceed the `MaxFileSizeKb` property of your module's `Cache`.

For your reference:
* `FileModule.ContentCaching` is `true` by default;
* the default `Cache` is `FileCache.Default`, whose default `MaxFileSizeKb` (also stored in the `FileCache.DefaultMaxFileSizeKb` constant) is 10240.

In order to determine whether the behavior you are experiencing is due to a bug, we need you to confirm that your file is smaller than 10 megabytes, and you haven't modified any of the properties mentioned above.

**Comment by madnik7** [comment]
So, as I need content-length for any size offile, it means I can't use it
if I have 3 Gigabytes file?

**Comment by rdeago** [comment]
@madnik7 sorry for the terribly late answer.

Unfortunately, you're right. `FileModule` needs some modifications if we want to support this scenario.
