### ISSUE TITLE
Unable to disable logger in 2.3.1

### ISSUE THREAD

**Issue by shravan2x** [unosquare/embedio#478]
**Describe the bug**
Logger doesn't disable using documentation code in v2.3.1.

**To Reproduce**
1. Use code
```c#
Swan.Logging.Logger.UnregisterLogger<ConsoleLogger>();
WebServer server = new WebServer("http://localhost:9696/", RoutingStrategy.Regex);
server.RegisterModule(new WebApiModule());
server.Module<WebApiModule>().RegisterController<ApiController>((context) => new ApiController(context));
server.RunAsync();
```

**Expected behavior**
Logger gets disabled.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 2.3.1

**Additional context**
Output is 
```
 11:09:02.815 INF >> [WebServer] Running HTTPListener: Unosquare HTTP Listener
 11:09:02.831 INF >> [WebServer] Web server prefix 'http://localhost:9696/' added.
 11:09:02.831 INF >> [WebServer] Finished Loading Web Server.
 11:09:02.900 INF >> [WebServer] Started HTTP Listener
```

**Comment by rdeago** [comment]
Hello @shravan2x, thanks for using EmbedIO!

Unfortunately, the berhavior you are experiencing is not due to a bug in EmbedIO, but rather in the (rather old) version of `Swan.Lite` used by version 2.3.1.

May I suggest you upgrade EmbedIO to the latest version?

You can find some basic information on how to upgrade your application to EmbedIO v3 [in the wiki](https://github.com/unosquare/embedio/wiki/Upgrade-from-v2). Should you need any more information or help, please feel free to [join us on Slack](https://join.slack.com/t/embedio/shared_invite/enQtNjcwMjgyNDk4NzUzLWQ4YTE2MDQ2MWRhZGIyMTRmNTU0YmY4MmE3MTJmNTY4MmZiZDAzM2M4MTljMmVmNjRiZDljM2VjYjI5MjdlM2U) to ask.

**Comment by shravan2x** [comment]
@rdeago You're right, that resolved my issue. Thanks for the quick response!
