### ISSUE TITLE
Error in connection establishment: net::ERR_SSL_OBSOLETE_VERSION

### ISSUE THREAD

**Issue by daihy8759** [unosquare/embedio#497]
System Version: Win7
Browser: Chrome

if i disable chrome flags: chrome://flags/#legacy-tls-enforced, it works. How to Solve this problem on Server?

**Comment by rdeago** [comment]
Hello @daihy8759, thanks for using EmbedIO! Sorry for the very late answer.

In order to better identify the cause of your issue, we need to know more about your use case:

- the version of EmbedIO you are using;
- operating system of the server, including version;
- whether you are using `HttpListenerMode.EmbedIO` or `HttpListenerMode.Microsoft`;
- if at all possible, your server initialization code.
