### ISSUE TITLE
Getting Help

### ISSUE THREAD

**Issue by tiziano-morgia** [unosquare/embedio#498]
**Is your feature request related to a problem? Please describe.**

Hello, 
  I found you, reading source code of an open source application (they used, of course, an EmbedIO inside) and I'm very happy for that! You saved me a lot of work writing my own local server.
  Actually I have same doubts and I have not found a place, other this, where I can get help or documentation (I have read samples, source, readme, cookbook). So, sorry if I'm writing here and this is not the right place.
  My doubts/problems are:
* I have a WebApiController (WAC) and a WebSocket (WS). For project purpose I must use both mode (http GET and WebSocket) for receive values so: WAC exsposes a GET function that receive the value (i.e: a number), this value is used to update a property of a **shared class**, and via WS I must dispatch to all client connected that property was changed. Actually the only solution that I have found is to create a WebSocketClient inside WAC and call "myself" via WS. There is another way to do this? I thinking about "call WS broadcast" inside WAC but...I don't know if it is possible and how I can do it.
* I did not understand when I must use CancellationToken. Sometimes, in examples, you put this in running server method, sometimes not. It is obviously my poor knowledge of the subject, but from the examples found I could not understand much. There is a link/place where I can understand this?
* (this is for Swan) Is not clear how I can write log on different files (ie: two server instance on same application, different file for every webapicontroller) neither how I can implement my own logger. I have tried with a custom class (the idea was to write in richtextbox in a winform) with ILogger + IDispose + event "onlog" either implementing ILogger directly in form without success. If I create log form and call Logger.xxx("message") works, al logging inside web server are not triggered (same place where log works, of course).

Thanks in advance and sorry for my english,
Tiziano.

**Describe the solution you'd like**

* A place like a forum (especially if it is not the right place to ask questions) where search solution, ask help, etc...
* Some rules for writing examples and upload it for community use (ie: the answer to my first question could become a prototype for others. obviously I could publish a generic version of the implementation knowing how and where to do it)

**Comment by rdeago** [comment]
Hello @tiziano-morgia, thanks for using EmbedIO! Sorry for the late answer.

The answer to your first question is rather simple: create an event in your shared class and trigger it every time the property is updated. Then listen to the event in your websocket controller, so you can broadcast the new value when necessary without involving the WebApiController at all.

The CancellationToken you see practically everywhere in EmbedIO modules is triggered when the server stops. If you perform any lengthy operation while handling a request, you should call its IsCancellationRequested method and abort anything you're doing when it returns `true` - or better, assuming that you handle unmanaged resources properly via using blocks / statements, just call ThrowIfCancellationRequested.

Although questions about SWAN are better asked [on its own repository](https://github.com/unosquare/swan/issues), here's a quick check list in the hope that it might help you:

- your logger is not automatically disposed by SWAN, so in the case of a RichTextBox you have to call Logger.UnregisterLogger just before your form closes;
- use Logger.RegisterLogger<T> only if you logger class has a public parameterless constructor, otherwise create an instance yourself and use the non-generic RegisterLogger.

Finally, we don't have a forum but you can [join us on Slack](https://join.slack.com/t/embedio/shared_invite/enQtNjcwMjgyNDk4NzUzLWQ4YTE2MDQ2MWRhZGIyMTRmNTU0YmY4MmE3MTJmNTY4MmZiZDAzM2M4MTljMmVmNjRiZDljM2VjYjI5MjdlM2U). Although your English is certainly more than good enough, feel free to write a direct message to me on Slack in Italian if you want.
